CREATE TABLE IF NOT EXISTS trade (
  tradeId BIGINT PRIMARY KEY,
  createTime BIGINT NOT NULL,
  price FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS trade_leg (
  tradeLegId BIGINT PRIMARY KEY,
  tradeId BIGINT NOT NULL REFERENCES trade,
  orderId BIGINT NOT NULL REFERENCES order_base,
  quantity INT NOT NULL
);