CREATE TYPE CUSTOMER_STATUS AS ENUM ('ACTIVE', 'INACTIVE');

CREATE TABLE IF NOT EXISTS customer (
  customerId BIGINT PRIMARY KEY,
  customerKey VARCHAR NOT NULL UNIQUE,
  status CUSTOMER_STATUS NOT NULL
);