CREATE TYPE ASSET_CLASS AS ENUM ('EQUITY', 'OPTION', 'FUTURE');

ALTER TABLE instrument ADD COLUMN symbol VARCHAR NOT NULL;
ALTER TABLE instrument ADD COLUMN assetClass ASSET_CLASS NOT NULL;
ALTER TABLE instrument ADD COLUMN description VARCHAR NOT NULL;
ALTER TABLE instrument ADD COLUMN expirationTime BIGINT NOT NULL;