on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to approve'
        required: true
        type: string

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
       contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Approve PR
        run: |
          gh pr review ${{ inputs.pr_number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.CODEOWNER_PR_RW_TOKEN }}
